### ISSUE TITLE
有什么办法可以获取ssh 终端session中的输入命令吗？

### ISSUE THREAD

**Issue by shencan** [a28283878/go_ssh_terminal#1]

**Comment by a28283878** [comment]
抱歉，你的問題可能要再具體一點

**Comment by shencan** [comment]
通过 ssh_main_conn.go可以实现远程机器的登录和连接, 我想实现在当前seesion下 记录用户输入的命令,以便实现审计功能

**Comment by a28283878** [comment]
應該可以透過Session.Stdin跟Session.Stdout來讀取使用者的輸入。詳細資訊可以查看下面的document。
https://godoc.org/golang.org/x/crypto/ssh#Session
